server:
   protocol: 'http'
   hostname: 'localhost'
   port: 3000

security:
    refkey: secretinformation
    passphrase: seconprivatekey
    pwdkey: passwordsecret
    verkey: accountversecret
    accexp: 1s
    refexp: 30d
    pwdexp: 30m
    verexp: 1w 

email:
    service: 'gmail'
    user: 'aox.mailer@gmail.com'
    pass: 'Iamdavid7D'

database:
    client: postgresql
    connection:
        database: auth-manager
        host: 'aox.hopto.org'
        port: 3001
        user: admin
        password: admin
    migrations:
        tableName: knex_migrations
        directory: ./src/models/migrations
    pool:
        min: 2
        max: 10