server:
   protocol: 'http'
   hostname: 'localhost'
   port: 3000

security:
    refkey: secretinformation
    passphrase: seconprivatekey
    accexp: 1s
    refexp: -1d

database:
    client: postgresql
    connection:
        database: auth-manager
        host: 'aox.hopto.org'
        port: 3001
        user: admin
        password: admin
    migrations:
        tableName: knex_migrations
        directory: ./src/models/migrations
    pool:
        min: 2
        max: 10